#!/usr/bin/env python3
"""Build the manuscript-facing interpreted docking-hit table.

This script keeps the pharmacology/status interpretation auditable: the
analysis output stays frozen, while this manuscript table is regenerated by
joining a small explicit interpretation map to the frozen prioritization table.
"""

from pathlib import Path

import pandas as pd


PROJECT_DIR = Path(__file__).resolve().parents[1]
SOURCE = PROJECT_DIR / "ml" / "results" / "meta_analysis" / "docking_headline_hits.csv"
OUTPUT = PROJECT_DIR / "manuscript" / "table_docking_headline_hits_interpreted.csv"

INTERPRETATION = {
    "DB05552": {
        "pharmacology_status": "investigational_non_gpcr_chemical_matter",
        "evidence_category": "chemical_starting_point",
        "candidate_claim_allowed": "no_experimental_starting_point",
        "status_note": (
            "TG100-115 is investigational chemical matter annotated in DrugBank "
            "against PI3K isoforms rather than ADORA2A; treat as a structural "
            "starting point, not as marketed-drug repurposing evidence."
        ),
    },
    "DB06229": {
        "pharmacology_status": "known_investigational_target_pharmacology",
        "evidence_category": "rediscovery_style_pharmacological_sanity_check",
        "candidate_claim_allowed": "no_known_pharmacology",
        "status_note": (
            "Ocaperidone is an investigational antipsychotic annotated with D2 "
            "receptor pharmacology; the result supports recovery of known target "
            "pharmacology rather than a "
            "novel repurposing claim."
        ),
    },
    "DB09168": {
        "pharmacology_status": "illicit_known_class_opioid_signal",
        "evidence_category": "hazard_caveat_row_not_repurposing_lead",
        "candidate_claim_allowed": "no_hazard_known_class",
        "status_note": (
            "4-Phenylfentanyl should be presented as a chemically plausible "
            "but hazardous known-class opioid signal, not as a promoted "
            "candidate."
        ),
    },
}


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Source table not found: {SOURCE}")

    hits = pd.read_csv(SOURCE)
    interp = (
        pd.DataFrame.from_dict(INTERPRETATION, orient="index")
        .rename_axis("drugbank_id")
        .reset_index()
    )
    out = hits.merge(interp, on="drugbank_id", how="left", validate="one_to_one")

    missing = out.loc[out["pharmacology_status"].isna(), "drugbank_id"].tolist()
    if missing:
        raise ValueError(f"No interpretation mapping for DrugBank IDs: {missing}")

    front = [
        "target",
        "unit",
        "drugbank_id",
        "generic_name",
        "pharmacology_status",
        "evidence_category",
        "candidate_claim_allowed",
        "status_note",
    ]
    out = out[front + [c for c in out.columns if c not in front]]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(OUTPUT, index=False)
    print(f"Wrote {OUTPUT} ({len(out)} prioritized compounds)")


if __name__ == "__main__":
    main()
